# Makepkg tweaks
CFLAGS="-march=native -O3 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection -flto=auto"
CXXFLAGS="$CFLAGS"
MAKEFLAGS="-j$(nproc)"
NINJAFLAGS="-j$(nproc)"
LDFLAGS="-Wl,-O3,--gc-sections,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C debuginfo=0 -C opt-level=3 -C target-cpu=native"

# Compression flags
COMPRESSZST=(zstd -c -z -q --threads=0 -)
COMPRESSXZ=(xz -c -z --threads=0 -)
COMPRESSGZ=(pigz -c -f -n)
COMPRESSBZ2=(pbzip2 -c -f)

# Other
GITFLAGS="--filter=tree:0"
